//
// Generated file, do not edit! Created by opp_msgtool 6.1 from message.msg.
//

#ifndef __MESSAGE_M_H
#define __MESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class subtask;
class subtaskResp;
class gossip;
/**
 * Class generated from <tt>message.msg:1</tt> by opp_msgtool.
 * <pre>
 * message subtask
 * {
 *     int client_id;
 *     int server_id;
 *     int arr_len;
 *     int query[];
 *     int TaskNum;
 *     int subTaskNum;
 *     bool IsMalicious;
 *     simtime_t timestamp;
 * }
 * </pre>
 */
class subtask : public ::omnetpp::cMessage
{
  protected:
    int client_id = 0;
    int server_id = 0;
    int arr_len = 0;
    int *query = nullptr;
    size_t query_arraysize = 0;
    int TaskNum = 0;
    int subTaskNum = 0;
    bool IsMalicious = false;
    omnetpp::simtime_t timestamp = SIMTIME_ZERO;

  private:
    void copy(const subtask& other);

  protected:
    bool operator==(const subtask&) = delete;

  public:
    subtask(const char *name=nullptr, short kind=0);
    subtask(const subtask& other);
    virtual ~subtask();
    subtask& operator=(const subtask& other);
    virtual subtask *dup() const override {return new subtask(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getClient_id() const;
    virtual void setClient_id(int client_id);

    virtual int getServer_id() const;
    virtual void setServer_id(int server_id);

    virtual int getArr_len() const;
    virtual void setArr_len(int arr_len);

    virtual void setQueryArraySize(size_t size);
    virtual size_t getQueryArraySize() const;
    virtual int getQuery(size_t k) const;
    virtual void setQuery(size_t k, int query);
    virtual void insertQuery(size_t k, int query);
    [[deprecated]] void insertQuery(int query) {appendQuery(query);}
    virtual void appendQuery(int query);
    virtual void eraseQuery(size_t k);

    virtual int getTaskNum() const;
    virtual void setTaskNum(int TaskNum);

    virtual int getSubTaskNum() const;
    virtual void setSubTaskNum(int subTaskNum);

    virtual bool getIsMalicious() const;
    virtual void setIsMalicious(bool IsMalicious);

    virtual omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(omnetpp::simtime_t timestamp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const subtask& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, subtask& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>message.msg:12</tt> by opp_msgtool.
 * <pre>
 * message subtaskResp
 * {
 *     int serverId;
 *     int clientId;
 *     int answer;
 *     int TaskNum;
 *     int SubTaskNum;
 *     simtime_t timestamp;
 * }
 * </pre>
 */
class subtaskResp : public ::omnetpp::cMessage
{
  protected:
    int serverId = 0;
    int clientId = 0;
    int answer = 0;
    int TaskNum = 0;
    int SubTaskNum = 0;
    omnetpp::simtime_t timestamp = SIMTIME_ZERO;

  private:
    void copy(const subtaskResp& other);

  protected:
    bool operator==(const subtaskResp&) = delete;

  public:
    subtaskResp(const char *name=nullptr, short kind=0);
    subtaskResp(const subtaskResp& other);
    virtual ~subtaskResp();
    subtaskResp& operator=(const subtaskResp& other);
    virtual subtaskResp *dup() const override {return new subtaskResp(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getServerId() const;
    virtual void setServerId(int serverId);

    virtual int getClientId() const;
    virtual void setClientId(int clientId);

    virtual int getAnswer() const;
    virtual void setAnswer(int answer);

    virtual int getTaskNum() const;
    virtual void setTaskNum(int TaskNum);

    virtual int getSubTaskNum() const;
    virtual void setSubTaskNum(int SubTaskNum);

    virtual omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(omnetpp::simtime_t timestamp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const subtaskResp& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, subtaskResp& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>message.msg:21</tt> by opp_msgtool.
 * <pre>
 * message gossip
 * {
 *     int txId;
 *     int rxId;
 *     int TaskNum;
 *     int serverScore[];
 *     simtime_t timestamp;
 * }
 * </pre>
 */
class gossip : public ::omnetpp::cMessage
{
  protected:
    int txId = 0;
    int rxId = 0;
    int TaskNum = 0;
    int *serverScore = nullptr;
    size_t serverScore_arraysize = 0;
    omnetpp::simtime_t timestamp = SIMTIME_ZERO;

  private:
    void copy(const gossip& other);

  protected:
    bool operator==(const gossip&) = delete;

  public:
    gossip(const char *name=nullptr, short kind=0);
    gossip(const gossip& other);
    virtual ~gossip();
    gossip& operator=(const gossip& other);
    virtual gossip *dup() const override {return new gossip(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getTxId() const;
    virtual void setTxId(int txId);

    virtual int getRxId() const;
    virtual void setRxId(int rxId);

    virtual int getTaskNum() const;
    virtual void setTaskNum(int TaskNum);

    virtual void setServerScoreArraySize(size_t size);
    virtual size_t getServerScoreArraySize() const;
    virtual int getServerScore(size_t k) const;
    virtual void setServerScore(size_t k, int serverScore);
    virtual void insertServerScore(size_t k, int serverScore);
    [[deprecated]] void insertServerScore(int serverScore) {appendServerScore(serverScore);}
    virtual void appendServerScore(int serverScore);
    virtual void eraseServerScore(size_t k);

    virtual omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(omnetpp::simtime_t timestamp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const gossip& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, gossip& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline subtask *fromAnyPtr(any_ptr ptr) { return check_and_cast<subtask*>(ptr.get<cObject>()); }
template<> inline subtaskResp *fromAnyPtr(any_ptr ptr) { return check_and_cast<subtaskResp*>(ptr.get<cObject>()); }
template<> inline gossip *fromAnyPtr(any_ptr ptr) { return check_and_cast<gossip*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MESSAGE_M_H

